site_name: OpenShift Knowledge Base
site_url: https://empty1957.github.io/vscode-obsidian-openshift/

theme:
  name: material

docs_dir: docs

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - ezlinks:
      wikilinks: true
  - git-revision-date-localized:
      enable_creation_date: true
      locale: ja
      timezone: Asia/Tokyo
